### PR TITLE
📚 DOCS: Add API documentation

### PR DESCRIPTION
**Pull request by chrisjsewell**

### CODE REVIEW

**Comment by chrisjsewell** [comment]
@choldgraf can you add ebp-bot to https://readthedocs.org/projects/markdown-it-py/

**Comment by choldgraf** [comment]
I just added you to a bunch of readthedocs pages as well...lemme know if I missed something. I don't want to be a permissions bottleneck on anything 👍

**Comment by chrisjsewell** [comment]
Maybe also https://readthedocs.org/projects/executablebookproject/ (it needs rerunning to update contributing.md)

**Comment by choldgraf** [comment]
done - god I wish RTD let us add github groups or something

**Comment by choldgraf** [comment]
guess we'll get that feature whenever Microsoft launches an Azure-subsidized documentation hosting platform that puts RTD out of business ;-)

**Pull request merged**
