### PR TITLE
📚 DOCS: Fix docstring

### PR DESCRIPTION
**Pull request by tsutsu3**
before:
before

after:
after

### CODE REVIEW

**Comment by tsutsu3** [comment]
Ref: https://github.com/actions/setup-python/issues/171

**Comment by hukkinj1** [comment]
Maybe change `pypy3` to `pypy-3.6` or `pypy-3.7` (or both) in CI as suggested in https://github.com/actions/setup-python/issues/171#issuecomment-747917974 ? That seems like the better syntax to me. It wasn't used originally here because it didn't exist yet at the time.

**Comment by tsutsu3** [comment]
It has been fixed to work with  `pypy3`

**Comment by tsutsu3** [comment]
> Ref: [actions/setup-python#171](https://github.com/actions/setup-python/issues/171)

It has been fixed to work with  `pypy3`

**Comment by chrisjsewell** [comment]
cheers, note it won't actually show in the documentation site until https://github.com/executablebooks/markdown-it-py/pull/101 is fixed

**Pull request merged**
