### PR TITLE
🐛 FIX: Always suffix indented code block with newline

### PR DESCRIPTION
**Pull request by hukkin**
I'll propose this change upstream and add a link here soon. Probably don't want to merge before accepted upstream.

EDIT: Here's the upstream PR https://github.com/markdown-it/markdown-it/pull/799

### CODE REVIEW

**Comment by hukkin** [comment]
Upstream PR is merged so this should be good to go. Would probably be good to do https://github.com/executablebooks/markdown-it-py/pull/168 first though, and then rebase this on master and update `port.yaml`.

**Comment by chrisjsewell** [comment]
cheers, will try to have a look in the not too distant future

**Comment by chrisjsewell** [comment]
I guess this can now be incorporated into a https://github.com/markdown-it/markdown-it/compare/12.1.0...12.2.0 sync

**Comment by hukkin** [comment]
> I guess this can now be incorporated into a markdown-it/markdown-it@12.1.0...12.2.0 sync

Yeah. I don't have the time to do that right now, but did rebase and update port.yaml. So this should also be mergeable as is.

**Comment by chrisjsewell** [comment]
>  I don't have the time to do that right now

tssk, so lazy 😜 yeh no worries, there is nothing in there that is a big priority and plenty busy myself

**Pull request merged**
