### PR TITLE
🐛 FIX: Crash when file ends with empty blockquote line

### PR DESCRIPTION
**Pull request by hukkin**
Closes https://github.com/executablebooks/markdown-it-py/issues/185

### CODE REVIEW

**Comment by chrisjsewell** [comment]
thanks @hukkin.
Given what I mentioned in https://github.com/executablebooks/markdown-it-py/pull/186, I'm thinking maybe we should just change https://github.com/executablebooks/markdown-it-py/blob/465b54d79641a3acd1d4e2ff483f1ccf4a4556ff/markdown_it/ruler.py#L50

so that it sets a "defaulttuple" that return None on out-of-bounds indexes?

**Comment by chrisjsewell** [comment]
PS, ignore the docs error; that's a circular dependency issue that will be fixed when I release a new myst-nb

**Comment by hukkin** [comment]
> I'm thinking now, maybe we should just change ... to defaulttuple

Yeah I'd like that as well. I would suggest
- Merge this to not delay fixing the known issue
- Work on defaulttuple in a separate PR. We have workarounds similar to the one in this PR elsewhere in the codebase as well, so there should an attempt to remove those in the defaulttuple PR.

> PS, ignore the docs error; that's a circular dependency

Yep, thanks for the heads up.

**Review by chrisjsewell — APPROVED** [review]

**Comment by hukkin** [comment]
The only issue I see with the defaulttuple approach is that if `self.srcCharCode` was intended as a performance hack, then moving from tuple index access to a function call may not be great for perf at all.

**Comment by chrisjsewell** [comment]
Could you not just create a simple https://docs.python.org/3/library/collections.abc.html#collections.abc.Sequence, that has `__getitem__` as a try/except

**Comment by hukkin** [comment]
Hmm perhaps but I wonder if you lose all C level optimization of the tuple datatype. Should probably just measure performance and see what's relevant and what's not.

**Comment by chrisjsewell** [comment]
Sure ting 👍

**Pull request merged**
