### PR TITLE
📚 DOCS: Improve documentation for CLI

### PR DESCRIPTION
**Pull request by westurner**

### CODE REVIEW

**Comment by westurner** [comment]
I ran `black cli/parse.py` and then `git commit --amend; git push -f` but the CI hasn't re-run (the pre-commit step)?

**Comment by westurner** [comment]
Where the interactive usage docs say `Type Ctrl-D to complete input, or Ctrl-C to exit.` is it necessary to always again mention that, in Windows, to do Ctrl-C, you enter `Ctrl-Z` and then `<return>`?

**Comment by westurner** [comment]
Does this need any more changes?

**Comment by chrisjsewell** [comment]
thats fine thanks

**Comment by westurner** [comment]
Thanks!

**Pull request merged**
