### PR TITLE
🐛 FIX: `_Entities.__contains__`

### PR DESCRIPTION
**Pull request by hukkinj1**

### CODE REVIEW

**Review by chrisjsewell — APPROVED** [review]

**Comment by hukkinj1** [comment]
@chrisjsewell btw, what do you think about replacing `markdown_it.common.entities.DATA` with
```python
import html
DATA = html.entities.html5
```

**Comment by chrisjsewell** [comment]
> what do you think about replacing markdown_it.common.entities.DATA with

they only have 106 keys in common, why the big difference?

```python
len(set(DATA).intersection(set(html.entities.html5))) == 106
```

**Comment by hukkinj1** [comment]
Ah, I see. `html.entities.html5` includes trailing semicolons whereas `DATA` does not. Explained here: https://docs.python.org/3/library/html.entities.html

Besides that I think the data should be the same.

**Comment by chrisjsewell** [comment]
yep thats more like it 👍 :

```python
len(set([_+';' for _ in DATA]).intersection(set(html.entities.html5))) == len(DATA)
```

so yeh, if we account for this trailing `;` in some fashion

**Pull request merged**
