### PR TITLE
🗑 DEPRECATE: `StateBase.srcCharCode`, `int` as input to `skipChars`, `skipCharsBack`, `isTerminatorChar`, `isLetter` and `isSpace`

### PR DESCRIPTION
**Pull request by hukkin**
Closes https://github.com/executablebooks/markdown-it-py/issues/198

Improves performance.

Deprecates:
- `StateBase.srcCharCode`
- Inputting codepoints as type `int` to `skipChars`, `skipCharsBack`, `isTerminatorChar`, `isLetter` and `isSpace`

### CODE REVIEW

**Comment by hukkin** [comment]
@chrisjsewell Regarding CI configuration: If you go to `Settings -> Branches -> Status checks that are required` you should be able to only require the "allgood" job and "readthedocs". That should also take care of those Python 3.6 jobs still showing up above.

**Comment by chrisjsewell** [comment]
> Regarding CI configuration: If you go to Settings -> Branches -> Status

Dude, I set all these GitHub actions across EBP, I know how to manage them 😜 I don't think the "all good" job is really necessary, but it's not hurting anyone 😂

**Comment by hukkin** [comment]
> I know how to manage them

Sorry, didn't mean to imply that you don't. Mainly just noting that this can now be configured, and trying to be helpful (I always look in `Settings -> Actions` first :facepalm: ).

> I don't think the "all good" job is really necessary,

Yeah definately not a necessity, but a nice convenience in that you no longer have to change these settings when adding py3.11 removing py3.7 etc.

**Comment by chrisjsewell** [comment]
Oh yeh no worries, I'll look at this stuff soonish 👍

**Comment by chrisjsewell** [comment]
If you want to fix the conflicts, then we can re-look at this cheers

**Comment by hukkin** [comment]
Fixed conflicts

**Comment by hukkin** [comment]
@chrisjsewell I know it's a bit rude to ask, but would you have time to give this a round of review any time soonish?

I'm asking because I'd like to port some changes from upstream and add some missing type annotations, but wouldn't want to get into a cycle of fixing merge conflicts in this or my future PRs.

**Comment by chrisjsewell** [comment]
Hey @hukkin, I think to move forward on this, could you first extract a separate PR that just does all the *non-controversial* changes, that just internally switch comparisons from ords to chars, like: 

```diff
-    if state.srcCharCode[pos] != 0x3C:  # /* < */
+    if state.src[pos] != "<":
```

and no changes that add warnings, or change function signatures, etc

**Comment by chrisjsewell** [comment]
Superseded by [f52249e](https://github.com/executablebooks/markdown-it-py/commit/f52249e1c26c7e66c8504848f582fcd3de85ab3d)

I added you as co-author, hope that's ok!

**Pull request closed without merging**
